/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package W18B_Group_5.Assignment1;

import W18B_Group_5.Assignment1.model.*;
import W18B_Group_5.Assignment1.view.*;
import javafx.application.Application;
import javafx.stage.Stage;


import java.sql.*;


public class App extends Application  {
    private Connection connection;

    @Override
    public void start(Stage primaryStage) throws Exception {

        try {
            connection = DriverManager.getConnection("jdbc:sqlite:database.db");
        } catch (SQLException e) {
            System.err.println("Could not connect to database");
            e.printStackTrace();
        }
        DatabaseSetup database = new DatabaseSetup(connection);
        DatabaseQuery dq = new DatabaseQueryImp(connection);

        primaryStage.setTitle("Xchange");

        // User screens
        UserSelectScreen userSelectScreen = new UserSelectScreen();
        UserFunctionScreen userFunctionScreen = new UserFunctionScreen();
        ExchangeScreen exchangeScreen = new ExchangeScreen(dq);
        SummaryScreen summaryScreen = new SummaryScreen(dq);
        Popular popularScreen = new Popular(dq);

        // Admin Screens
        AdminFunctionScreen adminFunctionScreen = new AdminFunctionScreen();
        AdminLogin adminLogin = new AdminLogin(primaryStage, adminFunctionScreen);
        UpdateExchangeRateScreen updateExchangeRateScreen = new UpdateExchangeRateScreen(dq);
        NewCurrencyScreen newCurrencyScreen = new NewCurrencyScreen(dq);
        ExchangeScreen adminExchangeScreen = new ExchangeScreen(dq);
        SummaryScreen adminSummaryScreen = new SummaryScreen(dq);
        Popular adminPopular = new Popular(dq);
        AdminChangePopular adminChangePopularScreen = new AdminChangePopular(dq);

        // Setting the button click events

        // User transitions
        userSelectScreen.setNormalUserEvent(
                e -> primaryStage.setScene(userFunctionScreen.getScene())
        );
        userFunctionScreen.setExchangeEvent(
                e -> primaryStage.setScene(exchangeScreen.getScene())
        );
        userFunctionScreen.setBackUserEvent(
                e -> primaryStage.setScene(userSelectScreen.getScene())
        );

        userFunctionScreen.setSummaryEvent(
                e -> primaryStage.setScene(summaryScreen.getScene())
        );
        userFunctionScreen.setPopularEvent(
                e -> primaryStage.setScene(popularScreen.getScene())
        );
        exchangeScreen.setBackExchangeEvent(
                e -> primaryStage.setScene(userFunctionScreen.getScene())
        );

        popularScreen.setBackExchangeEvent(
                e -> primaryStage.setScene(userFunctionScreen.getScene())
        );

        summaryScreen.setBackExchangeEvent(
                e -> primaryStage.setScene(userFunctionScreen.getScene())
        );



        // Admin transitions
        userSelectScreen.setAdminEvent(
                e -> primaryStage.setScene(adminLogin.getScene())
        );

        adminLogin.setBackUserSelectEvent(
                e -> primaryStage.setScene(userSelectScreen.getScene())
        );

        adminFunctionScreen.setExchangeEvent(
                e -> primaryStage.setScene(adminExchangeScreen.getScene())
        );
        adminFunctionScreen.setUpdateRateEvent(
                e -> primaryStage.setScene(updateExchangeRateScreen.getScene())
        );
        adminFunctionScreen.setAddCurrencyEvent(
                e -> primaryStage.setScene(newCurrencyScreen.getScene())
        );
        adminFunctionScreen.setBackAdminLogin(
                e -> primaryStage.setScene(adminLogin.getScene())
        );
        adminFunctionScreen.setSummaryEvent(
                e -> primaryStage.setScene(adminSummaryScreen.getScene())
        );
        adminFunctionScreen.setPopularEvent(
                e -> primaryStage.setScene(adminPopular.getScene())
        );
        adminFunctionScreen.setChangePopularEvent(
                e -> primaryStage.setScene(adminChangePopularScreen.getScene())
        );

        updateExchangeRateScreen.setBackAdminFunction(
                e -> primaryStage.setScene(adminFunctionScreen.getScene())
        );

        newCurrencyScreen.setBackAdminFunction(
                e -> primaryStage.setScene(adminFunctionScreen.getScene())
        );

        adminExchangeScreen.setBackExchangeEvent(
                e -> primaryStage.setScene(adminFunctionScreen.getScene())
        );

        adminSummaryScreen.setBackExchangeEvent(
                e -> primaryStage.setScene(adminFunctionScreen.getScene())
        );

        adminPopular.setBackExchangeEvent(
                e -> primaryStage.setScene(adminFunctionScreen.getScene())
        );

        adminChangePopularScreen.setBackAdminFunction(
                e -> primaryStage.setScene(adminFunctionScreen.getScene())
        );


        // Sets the initial scene that the app will display
        primaryStage.setScene(userSelectScreen.getScene());
        // Display the set scene
        primaryStage.show();

    }

    @Override
    public void stop() {
        try {
            connection.close();
        } catch (SQLException e) {
            System.err.println("Could not close database:");
            e.printStackTrace();
        }
    }

    public static void main(String[] args) {
        Application.launch(args);
    }



}
